function showcase(){var U='',R=' top: -1000px;',pb='" for "gwt:onLoadErrorFn"',nb='" for "gwt:onPropertyErrorFn"',$='");',qb='#',Vb='.cache.js',sb='/',yb='//',Ub=':',hb='::',T='<!doctype html>',V='<html><head><\/head><body><\/body><\/html>',kb='=',rb='?',mb='Bad handler "',S='CSS1Compat',Y='Chrome',X='DOMContentLoaded',M='DUMMY',Tb="GWT module 'showcase' may need to be (re)compiled",Ab='android',Cb='android_tablet',xb='base',vb='baseUrl',H='begin',Ib='blackberry',N='body',G='bootstrap',ub='clear.cache.gif',jb='content',Jb='desktop',Xb='end',Z='eval("',Ob='file://',I='gwt.codesvr.showcase=',J='gwt.codesvr=',ob='gwt:onLoadErrorFn',lb='gwt:onPropertyErrorFn',ib='gwt:property',db='head',O='iframe',tb='img',Db='ipad',Eb='ipad_retina',Fb='iphone',Gb='ipod',ab='javascript',P='javascript:""',Wb='loadExternalRefs',eb='meta',zb='mgwt.os',Bb='mobile',Kb='mobile.user.agent',Lb='mobilesafari',cb='moduleRequested',bb='moduleStartup',fb='name',Qb='no',Mb='not_mobile',Nb='phonegap.env',Q='position:absolute; width:0; height:0; border:none; left: -1000px;',Hb='retina',_='script',Rb='selectingPermutation',K='showcase',Sb='showcase.devmode.js',wb='showcase.nocache.js',gb='showcase::',L='startup',W='undefined',Pb='yes';var o=window;var p=document;r(G,H);function q(){var a=o.location.search;return a.indexOf(I)!=-1||a.indexOf(J)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:K,sessionId:o.__gwtStatsSessionId,subSystem:L,evtGroup:a,millis:(new Date).getTime(),type:b})}}
showcase.__sendStats=r;showcase.__moduleName=K;showcase.__errFn=null;showcase.__moduleBase=M;showcase.__softPermutationId=0;showcase.__computePropValue=null;showcase.__getPropMap=null;showcase.__gwtInstallCode=function(){};showcase.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[K]={moduleName:K};var v;function w(){y();return v}
function x(){y();return v.getElementsByTagName(N)[0]}
function y(){if(v){return}var a=p.createElement(O);a.src=P;a.id=K;a.style.cssText=Q+R;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();var b=document.compatMode==S?T:U;v.write(b+V);v.close()}
function z(k){function l(a){function b(){if(typeof p.readyState==W){return typeof p.body!=W&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(X,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(X,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=x();var f=w();var g;if(navigator.userAgent.indexOf(Y)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(Z));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode($));g=f.createElement(_);g.language=ab;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(_);g.language=ab;g.text=c[i];e.appendChild(g);d(e,g)}}}
showcase.onScriptDownloaded=function(a){l(function(){m(a)})};r(bb,cb);var n=p.createElement(_);n.src=k;p.getElementsByTagName(db)[0].appendChild(n)}
showcase.__startLoadingFragment=function(a){return C(a)};showcase.__installRunAsyncCode=function(a){var b=x();var c=w().createElement(_);c.language=ab;c.text=a;b.appendChild(c);b.removeChild(c)};function A(){var c={};var d;var e;var f=p.getElementsByTagName(eb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(fb),k;if(j){j=j.replace(gb,U);if(j.indexOf(hb)>=0){continue}if(j==ib){k=i.getAttribute(jb);if(k){var l,m=k.indexOf(kb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=U}c[j]=l}}else if(j==lb){k=i.getAttribute(jb);if(k){try{d=eval(k)}catch(a){alert(mb+k+nb)}}}else if(j==ob){k=i.getAttribute(jb);if(k){try{e=eval(k)}catch(a){alert(mb+k+pb)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;showcase.__errFn=e}
function B(){function e(a){var b=a.lastIndexOf(qb);if(b==-1){b=a.length}var c=a.indexOf(rb);if(c==-1){c=a.length}var d=a.lastIndexOf(sb,Math.min(c,b));return d>=0?a.substring(0,d+1):U}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(tb);b.src=a+ub;a=e(b.src)}return a}
function g(){var a=t(vb);if(a!=null){return a}return U}
function h(){var a=p.getElementsByTagName(_);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(wb)!=-1){return e(a[b].src)}}return U}
function i(){var a=p.getElementsByTagName(xb);if(a.length>0){return a[a.length-1].href}return U}
function j(){var a=p.location;return a.href==a.protocol+yb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==U){k=h()}if(k==U){k=i()}if(k==U&&j()){k=e(p.location.href)}k=f(k);return k}
function C(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return showcase.__moduleBase+a}
function D(){var f=[];var g;var h=[];var i=[];function j(a){var b=i[a](),c=h[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
i[zb]=function(){{var b=function(){var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(Ab)!=-1){if(a.indexOf(Bb)!=-1){return Ab}else{return Cb}}if(a.indexOf(Db)!=-1){if(window.devicePixelRatio>=2){return Eb}return Db}if(a.indexOf(Fb)!=-1||a.indexOf(Gb)!=-1){if(window.devicePixelRatio>=2){return Hb}return Fb}if(a.indexOf(Ib)!=-1){return Ib}return Jb}();return b}};h[zb]={android:0,android_tablet:1,blackberry:2,desktop:3,ipad:4,ipad_retina:5,iphone:6,retina:7};i[Kb]=function(){return /(android|iphone|ipod|ipad)/i.test(window.navigator.userAgent)?Lb:Mb};h[Kb]={mobilesafari:0,not_mobile:1};i[Nb]=function(){{var a=window.navigator.userAgent.toLowerCase();if(a.indexOf(Ab)!=-1||(a.indexOf(Db)!=-1||(a.indexOf(Gb)!=-1||(a.indexOf(Fb)!=-1||a.indexOf(Ib)!=-1)))){var b=document.location.href;if(b.indexOf(Ob)===0){return Pb}}return Qb}};h[Nb]={no:0,yes:1};s=function(a,b){return b in h[a]};showcase.__getPropMap=function(){var a={};for(var b in h){if(h.hasOwnProperty(b)){a[b]=j(b)}}return a};showcase.__computePropValue=j;o.__gwt_activeModules[K].bindings=showcase.__getPropMap;r(G,Rb);if(q()){return C(Sb)}var k;try{alert(Tb);return;var l=k.indexOf(Ub);if(l!=-1){g=parseInt(k.substring(l+1),10);k=k.substring(0,l)}}catch(a){}showcase.__softPermutationId=g;return C(k+Vb)}
function E(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(Wb,H);r(Wb,Xb)}
A();showcase.__moduleBase=B();u[K].moduleBase=showcase.__moduleBase;var F=D();E();r(G,Xb);z(F);return true}
showcase.succeeded=showcase();